name: auth_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.1
  equatable: ^2.0.8
  get_it: ^9.2.0
  dartz: ^0.10.1
  google_fonts: ^8.0.1
  go_router: ^17.1.0
  shared_preferences: ^2.5.4
  jwt_decoder: ^2.0.1
  connectivity_plus: ^6.1.0
  internet_connection_checker_plus: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/google.png
    - assets/icons/apple.png
